# shellcheck shell=bash
# Shared setup for the fixture commands. Sourced, never executed.

FIXTURES=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
STATE=$FIXTURES/.state
CACHE=$FIXTURES/.cache

# A BAO_TOKEN from the caller's own OpenBao or Vault work would win over the fixture's root token in
# bao() below. bin/evidence sets it on purpose, after this point.
unset BAO_TOKEN

set -a
# shellcheck source-path=SCRIPTDIR source=versions.env
. "$FIXTURES/versions.env"
if [ -f "$STATE/secrets.env" ]; then
  # shellcheck disable=SC1091  # generated by bin/up
  . "$STATE/secrets.env"
fi
set +a

# Keep every generated client config inside .state; never touch the caller's own.
export TALOSCONFIG=$STATE/talosconfig
export KUBECONFIG=$STATE/kubeconfig

PG=$FIXTURE_NAME-postgres
BAO=$FIXTURE_NAME-openbao
CP=$FIXTURE_NAME-controlplane-1
WORKER=$FIXTURE_NAME-worker-1

say() { printf '%s\n' "$*" >&2; }
die() {
  say "fixtures: $*"
  exit 1
}

need() {
  local tool
  for tool in "$@"; do
    command -v "$tool" >/dev/null || die "missing prerequisite: $tool"
  done
}

need_state() {
  [ -f "$STATE/secrets.env" ] || die "no running fixture: run fixtures/bin/up first"
}

# The project name is forced: a COMPOSE_PROJECT_NAME in the caller's shell wins over the `name` in
# compose.yaml, and every ownership check and teardown probe selects by that name's label.
compose() {
  docker compose --project-name "$FIXTURE_NAME" --project-directory "$FIXTURES" \
    --file "$FIXTURES/compose.yaml" \
    --env-file "$FIXTURES/versions.env" --env-file "$STATE/secrets.env" "$@"
}

talosctl() { "$CACHE/talosctl" "$@"; }

# bao <args>: the OpenBao CLI inside the pinned container, as root token unless BAO_TOKEN is set.
bao() {
  docker exec -e BAO_TOKEN="${BAO_TOKEN:-${BW_BAO_ROOT_TOKEN:-}}" "$BAO" bao "$@"
}

pg() { docker exec -e PGPASSWORD="$BW_POSTGRES_PASSWORD" "$PG" "$@"; }

# pg_client <psql args>: psql from a throwaway container on the fixture network. The image trusts
# every connection that starts inside the server's own container, so pg() proves nothing about the
# password; only a connection from another host is asked for it.
pg_client() {
  PGPASSWORD=$BW_POSTGRES_PASSWORD docker run --rm --network "${FIXTURE_NAME}_default" \
    --env PGPASSWORD "$POSTGRES_IMAGE" psql --host=postgres --username=bronzeward --dbname=bronzeward "$@"
}

# container <target>: map an injection target to a container name.
container() {
  case $1 in
    postgres) printf '%s\n' "$PG" ;;
    openbao) printf '%s\n' "$BAO" ;;
    controlplane) printf '%s\n' "$CP" ;;
    worker) printf '%s\n' "$WORKER" ;;
    *) die "unknown target '$1' (postgres, openbao, controlplane, worker)" ;;
  esac
}

# fetch <name> <url> <sha256>: download once into .cache, refuse a checksum mismatch.
fetch() {
  local name=$1 url=$2 sum=$3 file=$CACHE/download-$1
  mkdir -p "$CACHE"
  if [ ! -f "$file" ] || ! printf '%s  %s\n' "$sum" "$file" | sha256sum --check --status; then
    say "downloading $name"
    curl --fail --silent --show-error --location --output "$file" "$url"
    printf '%s  %s\n' "$sum" "$file" | sha256sum --check --status ||
      die "$name: sha256 mismatch for $url"
  fi
  printf '%s\n' "$file"
}

fetch_tools() {
  local file
  file=$(fetch talosctl "$TALOSCTL_URL" "$TALOSCTL_SHA256")
  install -m 0755 "$file" "$CACHE/talosctl"
  file=$(fetch sops "$SOPS_URL" "$SOPS_SHA256")
  install -m 0755 "$file" "$CACHE/sops"
  file=$(fetch age "$AGE_URL" "$AGE_SHA256")
  tar -xzf "$file" -C "$CACHE" --strip-components=1 age/age age/age-keygen
}

bao_unseal() {
  local key
  key=$(jq -r '.unseal_keys_b64[0]' "$STATE/bao-init.json")
  bao operator unseal "$key" >/dev/null
}

# wait_for <seconds> <description> <command...>
wait_for() {
  local limit=$1 what=$2 start=$SECONDS
  shift 2
  until "$@" >/dev/null 2>&1; do
    [ $((SECONDS - start)) -lt "$limit" ] || die "timed out after ${limit}s waiting for $what"
    sleep 1
  done
}
